# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/Product.proto for package 'rpc'

require 'grpc'
require 'Product_pb'

module Rpc
  module Products
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Products'

      rpc :GetProduct, GetProductReq, GetProductResp
    end

    Stub = Service.rpc_stub_class
  end
end
